name: GitHub CI

on: [push, pull_request]

jobs:
  build:
    name: Verify
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v5
    with:
      matrix-exclude: >
        [
          {"os": "macos-latest", "jdk": "8"},
          {"os": "macos-latest", "jdk": "21"},
          {"os": "windows-latest", "jdk": "21"}
        ]
      jdk-distribution-matrix: ' ["zulu"] '
      ff-jdk-distribution: 'zulu'
